main: me.mao.minigame.Core
name: day3
version: 0.0.3
commands:
  heal:
  join:
  leave:
  create:
  delete:
  remove:
  fstart:
  start:
  fstop:
  stop:
  j:
  l:
  c:
  arenas:
  listarenas:
  fcreate:
  rank:
  mr:
  menchant: