main: me.mao.minigame.Core
name: day3
version: 0.0.3
commands:
  heal:
  addspawn:
  as:
  acreate:
  ac:
  adelete:
  ad:
  astart:
  frs:
  astop:
  fs:
  ahelp:
  ah:
  ajoin:
  aj:
  aleave:
  alist:
  arenas:
  al:
  areload:
  arl:
  arenaspawns:
  arenastate:
  fcreate:
  rank:
  mr:
  tcreate:
  tdelete:
  tinvite:
  tinv:
  tkick:
  tleave:
  teams:
  listteams:
  tc:
  tremove:
  tl: